name: demo-action

on:
  push:
    branches:
      - main
      - master

jobs:
  DirActions:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - name: Show dir
        run: |
            pwd
      - name: List Dir
        run: |
           ls -al

  showSHA:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - name: Show SHA
        run: |
           echo $${{ github.sha }}
