name: demo-action

on:
  workflow_call:
    inputs:
      username:
        description: 'A Username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
        required: false

  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '30 5,17 * * *'

  push:
    branches:
      - main
    tags:
      - v1.*
    branches-ignore:
      - dev
    tags-ignore:
      - v2
  pull_request:
    branches:
      - main
  page_build:
    release:
      types:
        - created

jobs:
  Job_1_directory_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - name: Show dir
        run: |
            pwd
      - name: List Dir
        run: |
           ls -al

  Job_2_show_SHA:
    runs-on: ubuntu-latest
    needs: Job_1_directory_actions
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - name: Show vars
        run: |
          echo $${{ github.sha }}
          echo The GITHUB_ACTOR is ${{ github.actor }}
          echo The RUNNER_TEMP is ${{ runner.temp }}
  
  #Job_3_print_username:
  #  runs-on: ubuntu-latest
  #    steps:
  #      - name: Print Username to STDOUT
  #        run: echo The username is ${{ inputs.username }}